# Facade for the per-tier storage package. The public surface is unchanged from
# when storage was a single module: callers and tests keep importing
# `from vexic.storage import ...`. Internals now live in deep per-tier modules
# (schema, transcript, candidates, longterm) with `promotion` owning the
# cross-tier transaction; the dependency arrows point up only.

from vexic.storage.candidates import (
    DEDUP_MERGE_THRESHOLD,
    DEDUP_NEIGHBOR_COUNT,
    DEDUP_NO_MATCH_THRESHOLD,
    CandidateNote,
    DedupDecision,
    DedupMatch,
    DedupStats,
    PromotionCandidate,
    RemCandidate,
    RemStats,
    backfill_missing_candidate_embeddings,
    commit_dream_cycle,
    commit_rem_cycle,
    fetch_candidate_notes,
    keyword_candidate_ids,
    load_candidates_missing_embeddings,
    load_promotion_candidates,
    load_rem_candidates,
    nearest_candidate_ids,
    record_candidate_retrieval,
)
from vexic.storage.connection import StorageTarget
from vexic.storage.longterm import (
    LongTermFact,
    LongTermNeighbor,
    fetch_long_term_facts,
    keyword_long_term_fact_ids,
    nearest_long_term_facts,
    record_fact_use_verdict,
    record_long_term_retrieval,
    record_long_term_use,
)
from vexic.storage.operators import (
    MemoryExportReport,
    MemoryProjectionRepairReport,
    MemoryRebuildCopyReport,
    create_memory_rebuild_copy,
    export_memory_review,
    repair_memory_projections,
)
from vexic.storage.promotion import (
    CandidateRetirementDecision,
    DeepStats,
    PromotionDecision,
    commit_deep_cycle,
)
from vexic.storage.promotion_labels import (
    count_promotion_labels,
    record_promotion_label,
)
from vexic.storage.schema import (
    CATEGORY_CHECK,
    EMBEDDING_DISTANCE_METRIC,
    DreamStatus,
    _assert_no_forbidden_secret_values,
    init_db,
    init_vector_memory,
)
from vexic.storage.session_summaries import (
    SessionSummary,
    SessionSummaryKind,
    count_session_summaries_since,
    estimate_session_tokens,
    fetch_session_summary_frontier,
    find_session_compaction_span,
    list_compactable_session_ids,
    load_active_context_messages,
    load_fresh_context_rows,
    record_session_summary,
    render_session_recap,
    render_recap_blocks,
    render_compaction_source,
)
from vexic.storage.transcript import (
    SourceTranscriptIngestResult,
    SourceTranscriptInput,
    TranscriptHit,
    TranscriptRangeTooLarge,
    agent_watermarks,
    count_session_messages,
    get_watermark,
    ingest_source_messages,
    load_messages,
    load_messages_by_token_budget,
    load_messages_in_id_range,
    load_messages_since,
    message_search_text,
    messages_adapter,
    rebuild_messages_fts,
    save_messages,
    search_messages,
    single_message_adapter,
    strip_prompt_payloads,
)

# The facade preserves the full public surface of the former single module: the
# names callers and tests import, plus the non-underscore module-level names the
# old module exposed (dataclasses, dedup constants, message helpers), plus the
# one private `_assert_no_forbidden_secret_values` used by host adapters.
__all__ = [
    "CATEGORY_CHECK",
    "DEDUP_MERGE_THRESHOLD",
    "DEDUP_NEIGHBOR_COUNT",
    "DEDUP_NO_MATCH_THRESHOLD",
    "EMBEDDING_DISTANCE_METRIC",
    "CandidateNote",
    "CandidateRetirementDecision",
    "DedupDecision",
    "DedupMatch",
    "DedupStats",
    "DeepStats",
    "DreamStatus",
    "LongTermFact",
    "LongTermNeighbor",
    "MemoryExportReport",
    "MemoryProjectionRepairReport",
    "MemoryRebuildCopyReport",
    "PromotionCandidate",
    "PromotionDecision",
    "RemCandidate",
    "RemStats",
    "SessionSummary",
    "SessionSummaryKind",
    "SourceTranscriptIngestResult",
    "SourceTranscriptInput",
    "StorageTarget",
    "TranscriptHit",
    "TranscriptRangeTooLarge",
    "_assert_no_forbidden_secret_values",
    "backfill_missing_candidate_embeddings",
    "commit_deep_cycle",
    "commit_dream_cycle",
    "commit_rem_cycle",
    "count_promotion_labels",
    "create_memory_rebuild_copy",
    "estimate_session_tokens",
    "export_memory_review",
    "fetch_candidate_notes",
    "fetch_session_summary_frontier",
    "find_session_compaction_span",
    "fetch_long_term_facts",
    "get_watermark",
    "ingest_source_messages",
    "init_db",
    "init_vector_memory",
    "keyword_candidate_ids",
    "keyword_long_term_fact_ids",
    "load_candidates_missing_embeddings",
    "list_compactable_session_ids",
    "load_active_context_messages",
    "load_fresh_context_rows",
    "agent_watermarks",
    "count_session_messages",
    "load_messages",
    "load_messages_by_token_budget",
    "load_messages_in_id_range",
    "load_messages_since",
    "load_promotion_candidates",
    "load_rem_candidates",
    "message_search_text",
    "messages_adapter",
    "nearest_candidate_ids",
    "nearest_long_term_facts",
    "rebuild_messages_fts",
    "record_candidate_retrieval",
    "record_fact_use_verdict",
    "record_long_term_retrieval",
    "record_promotion_label",
    "count_session_summaries_since",
    "record_session_summary",
    "render_compaction_source",
    "render_recap_blocks",
    "render_session_recap",
    "record_long_term_use",
    "repair_memory_projections",
    "save_messages",
    "search_messages",
    "single_message_adapter",
    "strip_prompt_payloads",
]
